import os
import json
import requests
from openai import OpenAI

# 1. Required Environment Variables for OpenEnv Validator
API_BASE_URL = os.getenv("API_BASE_URL", "https://router.huggingface.co/v1")
MODEL_NAME = os.getenv("MODEL_NAME", "Qwen/Qwen2.5-7B-Instruct")
HF_TOKEN = os.getenv("HF_TOKEN", "hf_YOUR_TOKEN_HERE")

# 2. Your Live Hugging Face Space URL
BASE_URL = "https://benein-openenv-mobile-ui.hf.space"

# 3. Initialize the OpenAI Client (Routing to Hugging Face)
client = OpenAI(base_url=API_BASE_URL, api_key=HF_TOKEN)

SYSTEM_PROMPT = """
You are an autonomous UI testing agent. Your goal is to complete the assigned task by interacting with a mobile app's view hierarchy.
You will receive a JSON representation of the current screen. 

You must respond with a raw JSON object representing your next action. Do not include markdown formatting or explanations.
The JSON must strictly match this schema:
{
  "action_type": "tap" | "input_text" | "swipe" | "submit_audit",
  "target_node_id": "string (optional, required for tap/input_text)",
  "input_value": "string (optional, required for input_text)",
  "audit_report": ["list of strings (optional, required for submit_audit)"]
}
"""

def run_task(task_id: str, max_steps: int = 10):
    # REQUIRED LOGGING FORMAT: [START]
    print(f"[START] Task: {task_id}")
    
    try:
        # Reset environment
        response = requests.post(f"{BASE_URL}/reset", params={"task_id": task_id})
        response.raise_for_status()
        obs = response.json()
        
        for step in range(max_steps):
            user_prompt = f"Task: {task_id}\nObservation:\n{json.dumps(obs, indent=2)}\n\nNext Action?"
            
            # Query the model
            completion = client.chat.completions.create(
                model=MODEL_NAME,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.0
            )
            
            # REQUIRED LOGGING FORMAT: [STEP]
            print(f"[STEP] Step {step + 1}: Action generated by model")
            
            raw_action = completion.choices[0].message.content.strip()
            
            # Clean up potential markdown blocks from the LLM
            if "```json" in raw_action:
                raw_action = raw_action.split("```json")[1].split("```")[0].strip()
            elif "```" in raw_action:
                raw_action = raw_action.split("```")[1].split("```")[0].strip()
                
            action_payload = json.loads(raw_action)
            
            # Execute step in environment
            step_resp = requests.post(f"{BASE_URL}/step", json=action_payload).json()
            obs = step_resp["observation"]
            
            if step_resp["done"]:
                break
        
        # Get final grader score
        grader_resp = requests.get(f"{BASE_URL}/grader").json()
        score = grader_resp.get("score", 0.0)
        
        # REQUIRED LOGGING FORMAT: [END]
        print(f"[END] Task: {task_id} | Score: {score}")
        
    except Exception as e:
        # Ensure an [END] tag is printed even if there is an error
        print(f"[END] Task: {task_id} | Error: {str(e)}")

if __name__ == "__main__":
    tasks = ["task_1_easy", "task_2_medium", "task_3_hard"]
    for task in tasks:
        run_task(task)
